// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRw4e88PCP7E4te2GfbMS5rwQ-9MQG3ew',
    appId: '1:1069034772278:web:635b8d228fb8effb020597',
    messagingSenderId: '1069034772278',
    projectId: 'content-review-bbd55',
    authDomain: 'content-review-bbd55.firebaseapp.com',
    storageBucket: 'content-review-bbd55.firebasestorage.app',
    measurementId: 'G-KTSG7TWBFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpfScp5XxUeRdDO28kKE5ApEHBTH3Uhj8',
    appId: '1:1069034772278:android:d6144ddb20b94a10020597',
    messagingSenderId: '1069034772278',
    projectId: 'content-review-bbd55',
    storageBucket: 'content-review-bbd55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC67TgERuOWEWZnjD3qS1t5MVjLtJuDDdo',
    appId: '1:1069034772278:ios:b85a45c4277cbdcc020597',
    messagingSenderId: '1069034772278',
    projectId: 'content-review-bbd55',
    storageBucket: 'content-review-bbd55.firebasestorage.app',
    iosBundleId: 'com.example.contentManagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC67TgERuOWEWZnjD3qS1t5MVjLtJuDDdo',
    appId: '1:1069034772278:ios:b85a45c4277cbdcc020597',
    messagingSenderId: '1069034772278',
    projectId: 'content-review-bbd55',
    storageBucket: 'content-review-bbd55.firebasestorage.app',
    iosBundleId: 'com.example.contentManagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRw4e88PCP7E4te2GfbMS5rwQ-9MQG3ew',
    appId: '1:1069034772278:web:ec392650880a5efb020597',
    messagingSenderId: '1069034772278',
    projectId: 'content-review-bbd55',
    authDomain: 'content-review-bbd55.firebaseapp.com',
    storageBucket: 'content-review-bbd55.firebasestorage.app',
    measurementId: 'G-7YH03Y0S5T',
  );
}
